spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VitaliiRubezhanskii/financial-stock-broker-2.git
#          username: vitalii.rubezhanskii@gmail.com
#          password: Vitalik@1992
          searchPaths: configuration
      label: master

server:
  port: 8888

