spring:
  application:
    name: ${CONFIG_SERVICE_NAME}
  cloud:
    config:
      server:
        git:
          uri: ${GIT}
          #https://github.com/VitaliiRubezhanskii/financial-stock-broker-2.git
          searchPaths: ${FOLDER}
          #configuration
      label: ${BRANCH}
      #master



