spring:
  application:
    name: configserver

  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/VitaliiRubezhanskii/financial-stock-broker-2.git
          search-paths: configuration
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://monitoring:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true