spring:
  application:
    name: config_service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VitaliiRubezhanskii/financial-stock-broker-2.git
          searchPaths: configuration
          #configuration
      label: master
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery_service:8761/eureka/
server:
  port: 8888
      #master
#          default-label: docker



