spring:
  application:
    name: config_service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VitaliiRubezhanskii/financial-stock-broker-2
          searchPaths: configuration
          default-label: docker



