spring:
  application:
    name: configservice
  profiles:
    active: native
  cloud:
    config:
      server:
       git:
        uri: https://github.com/VitaliiRubezhanskii/financial-stock-broker-2.git
        searchPaths: configuration
      label: docker
#        native:
#          search-locations: ./configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
#        git:
#          uri: https://github.com/VitaliiRubezhanskii/financial-stock-broker-2.git
#          searchPaths: configuration
#          default-label: docker

server:
  port: 8888

