apiVersion: v1
kind: ConfigMap
metadata:
  name: order
  namespace: kafka
data:
  application.yml: |-
    
    spring:
      cloud:
        kubernetes.discovery.all-namespaces: "true"
      datasource:
        url: "jdbc:postgresql://postgres:5432/quotes_provider"
        password: "postgres"
        username: "postgres"
        driverClassName: "org.postgresql.Driver"
        hikari:
          connectionTimeOut: "2000"
          maximumPoolSize: "5"
      jpa:
        show-sql: "true"
        database-platform: "org.hibernate.dialect.PostgreSQL94Dialect"
        hibernate.ddl-auto: "update"
        properties:
          hibernate:
            dialect: "org.hibernate.dialect.PostgreSQLDialect"
            format_sql: "true"
            temp.use_jdbc_metadata_defaults: "false"
    security:
      oauth2:
        resourceserver:
          jwt:  
            jwk-set-uri: "http://192.168.64.8:30895/auth/realms/My-Realm/protocol/openid-connect/certs"
            
    security.basic.enabled: "false"
    server.port: "8080"