kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kafka
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding

subjects:
  - kind: ServiceAccount
    name: default
    namespace: kafka
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: namespace-reader
  apiGroup: ""

#              kubectl create clusterrolebinding namespace-reader-binding --clusterrole=namespace-reader --serviceaccount=default:namespace-reader-binding