version: "3"
networks:
    my-mongo-cluster:
      driver: bridge
services:
   mongo1:
      image: mongo:4.1.13-bionic
      command: --replSet rs0 --bind_ip_all
      ports:
        - 27018:27017
#      volumes:
#        - /etc/localtime:/etc/localtime:ro
#        - /mongo_cluster/data1:/data/db
      networks:
        - my-mongo-cluster
   mongo2:
      image: mongo:4.1.13-bionic
      command: --replSet rs0 --bind_ip_all
      ports:
        - 27019:27017
#      volumes:
#        - /etc/localtime:/etc/localtime:ro
#        - /mongo_cluster/data2:/data/db
      networks:
        - my-mongo-cluster
      depends_on:
        - mongo1
   mongo3:
      image: mongo:4.1.13-bionic
      command: --replSet rs0 --bind_ip_all
      ports:
        - 27020:27017
#      volumes:
#        - /etc/localtime:/etc/localtime:ro
#        - /mongo_cluster/data3:/data/db
      networks:
        - my-mongo-cluster
      depends_on:
       - mongo1
       - mongo2
   mongo-replicator:
      build:
        context: ./
        dockerfile: ./mongodb/Dockerfile
      networks:
        - my-mongo-cluster
      depends_on:
        - mongo1
        - mongo2
        - mongo3

   configservice:
       container_name: configservice
       image: config_service:latest

       healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:8888/account-service/dev"]
         interval: 30s
         timeout: 10s
         retries: 5

       build:
         context: ./support/config
         dockerfile: Dockerfile
       depends_on:
         - mongo-replicator
         - discovery
       environment:
         - JAVA_OPTS=
               -DEUREKA_SERVER=http://discovery:8761/eureka
               -Dspring.cloud.config.server.native.searchLocations=/var/configuration
       ports:
         - 8888:8888
       restart: always
       networks:
        - my-mongo-cluster

   discovery:
      container_name: discovery
      image: discovery_service:latest
      environment:
          CONFIG_SERVER: http://configservice:8888
      build:
        context: ./support/monitoring
        dockerfile: Dockerfile
      ports:
       - 8761:8761
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761"]
        interval: 30s
        timeout: 10s
        retries: 5

      restart: always
      networks:
       - my-mongo-cluster

   order_service:
      image: order_service:latest
      container_name: order_service
      environment:
            EUREKA_SERVER: http://discovery:8761/eureka
      ports:
       - 8082:8082
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:8081"]
         interval: 30s
         timeout: 10s
         retries: 5

      build:
        context: ./core/order-service
        dockerfile: Dockerfile
      depends_on:
           - mongo-replicator
           - discovery
           - configservice


      restart: always
      networks:
        - my-mongo-cluster

   account_service:
      container_name: account_service
      image: account_service:latest
      build:
        context: ./core/account-service
        dockerfile: Dockerfile
      depends_on:
          - mongo-replicator
          - discovery
          - configservice
      environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://discovery:8761/eureka
      ports:
             - 8081:8081
      healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8082"]
          interval: 30s
          timeout: 10s
          retries: 5
      restart: always
      networks:
        - my-mongo-cluster

   api_gateway_service:
      container_name: api_gateway_service
      expose:
       - 5000
      ports:
       - 5000:5000
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5000"]
        interval: 30s
        timeout: 10s
        retries: 5
      image: api_gateway_service:latest
      build:
        context: ./support/monitoring
        dockerfile: Dockerfile
      restart: always
      networks:
       - my-mongo-cluster