networks:
  my-mongo-cluster:
services:
  jenkins:
    hostname: jenkins
    image: vitalii1992/jenkins-fsb:v2
    build:
      context: jenkins
      dockerfile: jenkins/Dockerfile-Jenkins
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-mongo-cluster