networks:
  my-mongo-cluster:
services:
  jenkins:
    hostname: jenkins
    image: vitalii1992/jenkins-fsb:latest
    build:
      context: jenkins
      dockerfile: jenkins/Dockerfile-Jenkins
    ports:
      - 9001:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./jenkins/kubeconfig:/.kube
#      - /Users/vitalii/.m2/repository:/var/jenkins_home/.m2/repository
#      - /usr/local/Cellar/gradle/7.0.2_2:/var/jenkins_home/gradle/7.0.2_2
    networks:
      - my-mongo-cluster