version: "3.2"
networks:
    my-mongo-cluster:
services:
   mongo1:
      image: mongo:4.1.13-bionic
      command: --replSet rs0 --bind_ip_all
      ports:
        - 27018:27017
#      volumes:
#        - /etc/localtime:/etc/localtime:ro
#        - /mongo_cluster/data1:/data/db
      networks:
        - my-mongo-cluster
   mongo2:
      image: mongo:4.1.13-bionic
      command: --replSet rs0 --bind_ip_all
      ports:
        - 27019:27017
#      volumes:
#        - /etc/localtime:/etc/localtime:ro
#        - /mongo_cluster/data2:/data/db
      networks:
        - my-mongo-cluster
      depends_on:
        - mongo1
   mongo3:
      image: mongo:4.1.13-bionic
      command: --replSet rs0 --bind_ip_all
      ports:
        - 27020:27017
#      volumes:
#        - /etc/localtime:/etc/localtime:ro
#        - /mongo_cluster/data3:/data/db
      networks:
        - my-mongo-cluster
      depends_on:
       - mongo1
       - mongo2
   mongo-replicator:
      build:
        context: ./
        dockerfile: ./mongodb/Dockerfile
      networks:
        - my-mongo-cluster
      depends_on:
        - mongo1
        - mongo2
        - mongo3

   configserver:
       container_name: configserver
       expose:
        - 8888
       ports:
        - 8888:8888
       healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:8888/account-service/dev"]
         interval: 30s
         timeout: 10s
         retries: 5
       image: config_service:latest
       build:
         context: ./support/config
         dockerfile: Dockerfile
       depends_on:
         - mongo-replicator
         - discovery
       restart: always
       networks:
        - my-mongo-cluster

   discovery:
      container_name: discovery
      expose:
       - 8761
      ports:
       - 8761:8761
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761"]
        interval: 30s
        timeout: 10s
        retries: 5
      image: discovery_service:latest
      build:
        context: ./support/monitoring
        dockerfile: Dockerfile
      depends_on:
        - mongo-replicator
      restart: always
      networks:
       - my-mongo-cluster

   order:
      container_name: order_service
      expose:
        - 8082
      ports:
       - 8082:8082
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:8082"]
         interval: 30s
         timeout: 10s
         retries: 5
      image: order_service:latest
      build:
        context: ./core/order-service
        dockerfile: Dockerfile
      environment:
        PORT: 8082
      depends_on:
           - mongo-replicator
           - configserver
           - discovery
      restart: always
      networks:
        - my-mongo-cluster

   order2:
     container_name: order_service2
     expose:
       - 8092
     ports:
       - 8092:8092
     healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8092"]
       interval: 30s
       timeout: 10s
       retries: 5
     image: order_service:latest
     build:
       context: ./core/order-service
       dockerfile: Dockerfile
     environment:
       PORT: 8092
     depends_on:
       - mongo-replicator
       - configserver
       - discovery
     restart: always
     networks:
       - my-mongo-cluster

   account:
      container_name: account_service
      expose:
       - 8081
      ports:
       - 8081:8081
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8081"]
        interval: 30s
        timeout: 10s
        retries: 5
      image: account_service:latest
      build:
        context: ./core/account-service
        dockerfile: Dockerfile
      depends_on:
         - mongo-replicator
         - configserver
         - discovery
      restart: always
      networks:
        - my-mongo-cluster

   gateway:
      container_name: api_gateway_service
      expose:
       - 5000
      ports:
       - 5000:5000
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5000"]
        interval: 30s
        timeout: 10s
        retries: 5
      image: api_gateway_service:latest
      build:
        context: ./support/gateway
        dockerfile: Dockerfile
      depends_on:
        - mongo-replicator
        - configserver
        - discovery
      restart: always
      networks:
       - my-mongo-cluster

   feign:
       container_name: feign-hystrix-service
       ports:
         - 8099:8099
       image: feign-hystrix-service:latest
       build:
         context: ./support/feign-hystrix-client
         dockerfile: Dockerfile
       depends_on:
         - mongo-replicator
         - configserver
         - discovery
       restart: always
       networks:
         - my-mongo-cluster