version: "3.2"
networks:
  my-mongo-cluster:
services:
  jenkins:
    hostname: jenkins
    image: vitalii1992/jenkins-fsb:latest
    build:
      context: jenkins
      dockerfile: Dockerfile
    ports:
      - 9001:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/vitalii/Documents/01.FSB/financial-stock-broker-2/jenkins/kubeconfig:/.kube
      - /Users/vitalii/.m2/repository:/var/jenkins_home/.m2/repository
    networks:
      - my-mongo-cluster