apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: vitalii1992/api-gateway-service:latest #${REPOSITORY_TAG}
          ports:
            - containerPort: 5000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: gateway

spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: gateway
  type: LoadBalancer
  externalIPs:
    - 192.168.64.8