apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: account
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://vitaliirubezhanskii.github.io/financial-stock-broker-2-helm-charts.git
    targetRevision: HEAD
    path: charts/account
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

