apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring
  replicas: 1
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: monitoring
          image: discovery #${REPOSITORY_TAG}
          ports:
            - containerPort: 8761
          imagePullPolicy: Never

#          readinessProbe:
#            httpGet:
#              path: /eureka
#              port: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring

spec:
  selector:
    app: monitoring
  ports:
    - port: 8761
      protocol: TCP
  type: NodePort