apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: monitoring
          image: ${REPOSITORY_TAG}
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /eureka
              port: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: monitoring

  ports:
    - name: http
      port: 8761

  type: ClusterIP