apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  selector:
    matchLabels:
      app: analytics
  replicas: 1
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: vitalii1992/analytics-service:latest #${REPOSITORY_TAG}
          ports:
            - containerPort: 9010
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: '9010'
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: analytics

spec:
  ports:
    - port: 9010
      protocol: TCP
  selector:
    app: analytics
  type: LoadBalancer