apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: analytics
  replicas: 1
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: vitalii1992/analytics-service:latest #${REPOSITORY_TAG}
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: '8090'
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:063132795330:certificate/c094fd1f-962c-4847-9ba5-b4ed7bb3cae6
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30002
    - name: https
      port: 443
      targetPort: 80
  selector:
    app: analytics
  type: LoadBalancer