spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://configserver:8888

server:
  port: 5000

zuul:
  ignored-services: '*'
  routes:
    account: /account/**
    order: /order/**
    feign: /feign/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 138000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

hystrix:
  metrics:
    enabled: true
  enabled: true

management:
  endpoint:
    hystrix:
      stream:
        enabled: true
  endpoints:
    web:
        exposure:
          include: routes
