spring:
  application:
    name: api_gateway_service
  cloud:
    config:
      uri: http://configserver:8888

server:
  port: 5000

zuul:
  ignored-services: '*'
  routes:
    account: /account/**
    order: /order/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000