server:
  port: 8082
spring:
  application:
    name: order_service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery_service:8761/eureka}






