server:
  port: 8082
spring:
  application:
    name: order_service
  profiles:
    active: default
  cloud:
   config:
     uri: ${CONFIG_SERVER}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery_service:8761/eureka}







