server:
  port: 8082
spring:
  application:
    name: order-service
  cloud:
     config:
       uri: ${CONFIG_SERVER}
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/orders?replicaSet=rs0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery_service:8761/eureka}







