apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: ${REPOSITORY_TAG}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: 8092
            - name: CONFIGSERVER_URI
              value: http://configserver:8888
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /
              port: 8092
---
apiVersion: v1
kind: Service
metadata:
  name: order-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: order

  ports:
    - name: http
      port: 8092

  type: ClusterIP