apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: ${ORDER_SERVICE_IMAGE} #order-service #${REPOSITORY_TAG}
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: '8092'
            - name: ORDER_SERVICE_IMAGE
              value: vitalii1992/order-service:latest
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: order

spec:
  ports:
    - port: 8092
      protocol: TCP
  selector:
    app: order
  type: LoadBalancer