apiVersion: apps/v1
kind: Deployment
metadata:
  name: feign
spec:
  selector:
    matchLabels:
      app: feign
  replicas: 1
  template:
    metadata:
      labels:
        app: feign
    spec:
      containers:
        - name: feign
          image: vitalii1992/feign-service:latest #${REPOSITORY_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: feign
spec:
  selector:
    app: feign
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  type: NodePort