apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: vitalii1992/order-service:latest #${REPOSITORY_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: order

spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: order
  type: NodePort