apiVersion: v1
kind: Service
metadata:
 name: mongodb
 labels:
  name: mongodb
spec:
 ports:
 - port: 27017
   targetPort: 27017
 clusterIP: None
 selector:
   role: mongodb
---
#kind: Service
#apiVersion: v1
#metadata:
#  name: orderservice
#spec:
#  selector:
#    app: orderservice
#  ports:
#    - port: 8080
#      targetPort: 8080
#  type: ClusterIP

