apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: kafka
type: Opaque
data:
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=