kind: PersistentVolume
apiVersion: v1
metadata:
  name: keycloak-pv-volume
  namespace: kafka
  labels:
    type: local
    app: keycloak
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/keycloak/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-pv-claim
  namespace: kafka
  labels:
    app: keycloak
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi