kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-controller
  namespace: kafka
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""

data:
  use-forwarded-headers: "true"
  forwarded-for-header: "X-Forwarded-For"