apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics
  namespace: kafka
data:
  server.port: "9998"

  spring.cloud.stream.function.definition: "process"
  spring.cloud.stream.bindings.process-in-0.destination: "quote"
  spring.cloud.stream.bindings.process-out-0.destination: "quote-aggregation"
  spring.cloud.stream.bindings.process-out-0.producer.useNativeEncoding: "true"
  spring.cloud.stream.kafka.binder.brokers: "my-kafka-cluster-kafka-bootstrap:9092"
  spring.cloud.stream.kafka.bindings.process-in-0.consumer.configuration.schema.registry.url: "http://strimzi-registry-operator:8081"
  spring.cloud.stream.kafka.bindings.process-in-0.consumer.configuration.key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  spring.cloud.stream.kafka.bindings.process-in-0.consumer.configuration.value.deserializer: com.investment.serializer.SensorDeserializer
  spring.cloud.stream.kafka.bindings.process-in-0.consumer.configuration.process-out-0.producer.configuration.schema.registry.url: "http://strimzi-registry-operator:8081"
  spring.cloud.stream.kafka.bindings.process-in-0.consumer.configuration.process-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer
  spring.cloud.stream.kafka.bindings.process-in-0.consumer.configuration.process-out-0.producer.configuration.value.serializer: com.investment.serializer.SensorSerializer
  spring.cloud.stream.kafka.streams.binder.brokers: "my-kafka-cluster-kafka-bootstrap:9092"
  spring.cloud.stream.kafka.streams.binder.configuration.schema.registry.url: "http://strimzi-registry-operator:8081"
  spring.cloud.stream.kafka.streams.binder.specific.avro.reader: "true"

  spring.cloud.stream.kafka.streams.bindings.process-out-0.producer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
  spring.cloud.stream.kafka.streams.bindings.process-out-0.producer.valueSerde: com.investment.serde.SensorSerde

  spring.cloud.stream.kafka.streams.bindings.process-out-0.producer.process-in-0.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
  spring.cloud.stream.kafka.streams.bindings.process-out-0.producer.process-in-0.consumer.valueSerde: com.investment.serde.SensorSerde

