apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: analytics
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  labels:
    app: analytics
subsets:
  - addresses:
      - ip: 192.168.1.156
    ports:
      - port: 5432