apiVersion: v1
kind: Service
metadata:
  name: schemaregistry
  labels:
    app: analytics
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Endpoints
metadata:
  name: schemaregistry
  labels:
    app: analytics
subsets:
  - addresses:
      - ip: 192.168.1.156
    ports:
      - port: 8081