apiVersion: v1
kind: ConfigMap
metadata:
  name: account
data:
  spring.cloud.kubernetes.discovery.all-namespaces: "true"
  spring.data.mongodb.host: mongodb-service.default.svc.cluster.local
  spring.data.mongodb.port: '27017'
  spring.data.mongodb.username: admin
  spring.data.mongodb.password: password
  spring.data.mongodb.database: account
  spring.data.mongodb.authentication-database: admin
  spring.zipkin.enabled: 'true'
  spring.zipkin.baseUrl: http://tracing.default.svc.cluster.local:9411

  security.oauth2.client.clientId: account
  security.oauth2.client.clientSecret: '123'
  security.oauth2.client.accessTokenUri: http://auth.default.svc.cluster.local:8084/uaa/oauth/token
  security.oauth2.client.grant-type: client_credentials
  security.oauth2.client.scope: server
  server.port: '8085'

  security.oauth2.resource.user-info-uri: http://auth.default.svc.cluster.local:8084/uaa/user/current
  security.oauth2.resource.token-info-uri: http://auth.default.svc.cluster.local:8084/uaa/oauth/check_token