apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: kafka
  source:
    path: kind/argocd/manifests/kafka
    repoURL: https://github.com/VitaliiRubezhanskii/financial-stock-broker-2.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: account-service
  namespace: argocd
spec:
  project: account
  source:
    chart: account
    repoURL: https://vitaliirubezhanskii.github.io/financial-stock-broker-2-helm-charts
    targetRevision: 0.3.8
    helm:
      releaseName: account
  destination:
    server: "https://kubernetes.default.svc"