apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: kafka
  source:
    path: kind/argocd/manifests/kafka
    repoURL: https://github.com/VitaliiRubezhanskii/financial-stock-broker-2.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true