apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: kafka
  source:
    path: manifests/kafka
    repoURL: https://bitbucket.org/vrubezhanskii/financial-stock-broker-2
    targetRevision: develop
  syncPolicy:
    syncOptions:
      - CreateNamespace=true