apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  selector:
    matchLabels:
      app: analytics
  replicas: 1
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: vitalii1992/analytics-service:latest #analytics-service #${REPOSITORY_TAG}
          ports:
            - containerPort: 8093
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: '8093'
            - name: CONFIGSERVER_URI
              value: http://configserver.default.svc.cluster.local:8888
            - name: ANALYTICS_SERVICE_IMAGE
              value: "vitalii1992/analytics-service:latest"
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: analytics

spec:
  ports:
    - port: 8093
      protocol: TCP
  selector:
    app: analytics
  type: LoadBalancer