spring:
  profiles:
    active: development
  flyway:
    enabled: true
    validate-on-migrate: false
    baseline-on-migrate: true
server:
    port: 9000
management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: health,flyway,metrics
  server:
    port: 8081
    servlet:
      context-path: /admin
logging:
  level:
    cristina.tech: debug
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: error
---
spring:
  profiles: development
  flyway:
    baseline-on-migrate: true
    locations: classpath:migration
  datasource:
    url: jdbc:postgresql://localhost:5432/dresses
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximumPoolSize: 10
      connectionTimeout: 1500
  data:
    rest:
      detection-strategy: annotated
  cloud:
    stream:
      bindings:
        idresses:
          destination: dresses
          group: dresses-group
          contentType: application/json
          consumer:
            durableSubscription: true
            concurrency: 10
        iratings:
          destination: ratings
          concurrency: 10
          group: ratings-group
          content-type: application/json
          consumer:
            durableSubscription: true
            concurrency: 10
---
spring:
  profiles: docker
  flyway:
    baseline-on-migrate: true
    locations: classpath:migration
  datasource:
    url: jdbc:postgresql://postgresdb:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: demo
    hikari:
      maximumPoolSize: 10
      connectionTimeout: 1500
  data:
    rest:
      detection-strategy: annotated
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
      bindings:
        input:
          destination: dresses
          consumer:
            partitioned: false
        idresses:
          destination: dresses
          group: dresses-group
          contentType: application/json
          consumer:
            durableSubscription: true
            concurrency: 20
        iratings:
          destination: ratings
          group: ratings-group
          contentType: application/json
          consumer:
            durableSubscription: true
            concurrency: 20
#        input:
#          destination: ratings
      streams:
        binder:
         application-id: splitter
         brokers: localhost:9092
         configuration.default:
            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            value.serde: org.springframework.kafka.support.serializer.JsonSerde
            spring:
             json:
               key:
                 default:
                   type: java.lang.String
               default:
                 value:
                   type: com.investment.analytics.worker.event.DressMessageEvent


  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    com.investment.analytics: debug
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: error
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,flyway,metrics