spring:
  profiles:
    active: development
  flyway:
    enabled: true
    validate-on-migrate: false
    baseline-on-migrate: true
server:
    port: 9000
management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: health,flyway,metrics
  server:
    port: 8181
    servlet:
      context-path: /admin
logging:
  level:
    cristina.tech: debug
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: error
---
spring:
  profiles: development

  cloud:
    stream:
      bindings:
        idresses:
          destination: dresses
          group: dresses-group
          contentType: application/json
#          consumer:
#            durableSubscription: true
#            concurrency: 10
#        iratings:
#          destination: ratings
#          concurrency: 10
#          group: ratings-group
#          content-type: application/json
#          consumer:
#            durableSubscription: true
#            concurrency: 10
---
spring:
  profiles: docker

  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: kafka
      bindings:
#        input:
#          binder: kafka
#          destination: dresses
#          consumer:
#            partitioned: false
        idresses:
          binder: kafka
          destination: dresses
          group: dresses-group
          contentType: application/json
          consumer:
            durableSubscription: true
            concurrency: 20
#        iratings:
#          destination: ratings
#          group: ratings-group
#          contentType: application/json
#          consumer:
#            durableSubscription: true
#            concurrency: 20
#        input:
#          destination: ratings
        streams:
          binder:
           application-id: splitter
           brokers: kafka
           configuration.default:
              key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              value.serde: org.springframework.kafka.support.serializer.JsonSerde
              spring:
               json:
                 key:
                   default:
                     type: java.lang.String
                 default:
                   value:
                     type: com.investment.analytics.worker.event.DressMessageEvent



  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    com.investment.analytics: debug
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: error
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,flyway,metrics