apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  selector:
    matchLabels:
      app: configserver
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: configserver  #${REPOSITORY_TAG}
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /account/deployment
              port: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: configserver

  ports:
    - name: http
      port: 8888
      nodePort: 30030


  type: NodePort