apiVersion: apps/v1
kind: Deployment
metadata:
  name: feign
spec:
  selector:
    matchLabels:
      app: feign
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: feign
    spec:
      containers:
        - name: feign
          image: ${REPOSITORY_TAG}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: 8084
            - name: CONFIGSERVER_URI
              value: http://configserver:8888
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080

  type: ClusterIP