global:
  postgresql:
    auth:
      postgresPassword: "postgres"
      username: "postgres"
      password: "postgres"
      database: "quotes_provider"
primary:
  extendedConfiguration: |
    max_connections = 400
  initdb:
    scripts:
      my_init_script.sql: |
        create database keycloak;
        create user keycloak with encrypted password 'postgres';
        grant all privileges on database keycloak to keycloak;