#kc:
#  base-url: http://192.168.64.8:30895/auth
#  realm: My-Realm
#  realm-url: ${kc.base-url}/realms/${kc.realm}
#
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak-spring-gateway-client:
#            provider: my-keycloak-provider
#            scope: openid
#            client-id: spring-gateway-client
#            client-secret: 3RhEF8pqKTANrQ6BhfxaYVmcjTXsDK0u
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
#        provider:
#          my-keycloak-provider:
#            issuer-uri: ${kc.realm-url}
#            jwk-set-uri: ${kc.realm-url}/protocol/openid-connect/certs
#            authorization-uri: ${kc.realm-url}/protocol/openid-connect/auth
