apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway #${REPOSITORY_TAG}
          ports:
            - containerPort: 5000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: '5000'
            - name: CONFIGSERVER_URI
              value: http://configserver:8888
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: gateway

spec:

  selector:
    app: gateway

  ports:
    - port: 5000
      protocol: TCP

  type: NodePort