apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ${REPOSITORY_TAG}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: 5000
            - name: CONFIGSERVER_URI
              value: http://configserver:8888
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /
              port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: gateway

  ports:
    - name: http
      port: 5000

  type: ClusterIP