/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Quote extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1338828737994128440L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Quote\",\"namespace\":\"avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"ticket\",\"type\":\"string\",\"aliases\":[\"ticket\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Quote> ENCODER =
      new BinaryMessageEncoder<Quote>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Quote> DECODER =
      new BinaryMessageDecoder<Quote>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Quote> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Quote> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Quote>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Quote to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Quote from a ByteBuffer. */
  public static Quote fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence ticket;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Quote() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param ticket The new value for ticket
   */
  public Quote(java.lang.CharSequence id, java.lang.CharSequence ticket) {
    this.id = id;
    this.ticket = ticket;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return ticket;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: ticket = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'ticket' field.
   * @return The value of the 'ticket' field.
   */
  public java.lang.CharSequence getTicket() {
    return ticket;
  }

  /**
   * Sets the value of the 'ticket' field.
   * @param value the value to set.
   */
  public void setTicket(java.lang.CharSequence value) {
    this.ticket = value;
  }

  /**
   * Creates a new Quote RecordBuilder.
   * @return A new Quote RecordBuilder
   */
  public static avro.Quote.Builder newBuilder() {
    return new avro.Quote.Builder();
  }

  /**
   * Creates a new Quote RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Quote RecordBuilder
   */
  public static avro.Quote.Builder newBuilder(avro.Quote.Builder other) {
    return new avro.Quote.Builder(other);
  }

  /**
   * Creates a new Quote RecordBuilder by copying an existing Quote instance.
   * @param other The existing instance to copy.
   * @return A new Quote RecordBuilder
   */
  public static avro.Quote.Builder newBuilder(avro.Quote other) {
    return new avro.Quote.Builder(other);
  }

  /**
   * RecordBuilder for Quote instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Quote>
    implements org.apache.avro.data.RecordBuilder<Quote> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence ticket;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.Quote.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ticket)) {
        this.ticket = data().deepCopy(fields()[1].schema(), other.ticket);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Quote instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.Quote other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ticket)) {
        this.ticket = data().deepCopy(fields()[1].schema(), other.ticket);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public avro.Quote.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public avro.Quote.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ticket' field.
      * @return The value.
      */
    public java.lang.CharSequence getTicket() {
      return ticket;
    }

    /**
      * Sets the value of the 'ticket' field.
      * @param value The value of 'ticket'.
      * @return This builder.
      */
    public avro.Quote.Builder setTicket(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.ticket = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ticket' field has been set.
      * @return True if the 'ticket' field has been set, false otherwise.
      */
    public boolean hasTicket() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ticket' field.
      * @return This builder.
      */
    public avro.Quote.Builder clearTicket() {
      ticket = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Quote build() {
      try {
        Quote record = new Quote();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.ticket = fieldSetFlags()[1] ? this.ticket : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Quote>
    WRITER$ = (org.apache.avro.io.DatumWriter<Quote>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Quote>
    READER$ = (org.apache.avro.io.DatumReader<Quote>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
