server:
  additionalApplications:
    - name: cluster-config
      namespace: argocd
      project: default
      source:
        repoURL: https://bitbucket.org/vrubezhanskii/financial-stock-broker-2
        targetRevision: HEAD
        path: kind/argocd/manifests/cluster
        directory:
          recurse: true
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true