apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  selector:
    matchLabels:
      app: account
  replicas: 1
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: ${ACCOUNT_SERVICE_IMAGE} #account-service #${REPOSITORY_TAG}
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: '8085'
            - name: ACCOUNT_SERVICE_IMAGE
              value: vitalii1992/account-service:latest
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: account

spec:
  ports:
      - port: 8081
        protocol: TCP
  selector:
    app: account
  type: NodePort