apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  selector:
    matchLabels:
      app: account
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: ${REPOSITORY_TAG}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: 8081
            - name: CONFIGSERVER_URI
              value: http://configserver:8888
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /
              port: 8092
---
apiVersion: v1
kind: Service
metadata:
  name: account-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: account

  ports:
    - name: http
      port: 8081

  type: ClusterIP