spring:
  application:
    name: account-service
  cloud:
    config:
      uri: ${CONFIG_SERVER:http://configservice:8888}
      label: docker
      profile: default
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/orders?replicaSet=rs0
eureka:
  instance:
      preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery:8761/eureka}
server:
  port: 8081



