spring:
  application:
    name: account_service
  cloud:
   config:
     uri: ${CONFIG_SERVER:http://config_service:8888}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery_service:8761/eureka}



