server:
  port: 8081
spring:
  application:
    name: account_service
  cloud:
   config:
     uri: ${CONFIG_SERVER:http://config_service:8888}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery_service:8761/eureka}



