apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  selector:
    matchLabels:
      app: account
  replicas: 1
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: vitalii1992/account-service:latest #${REPOSITORY_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: account

spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: account
  type: NodePort