apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  selector:
    matchLabels:
      app: account
  replicas: 1
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: vitalii1992/account-service:latest #${REPOSITORY_TAG}
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: '8085'
            - name: CONFIGSERVER_URI
              value: http://configserver:8888
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: account

spec:
  ports:
      - port: 8081
        protocol: TCP
  selector:
    app: account
  type: NodePort