spring:
  profiles:
    active: default
---

spring:
  application:
    name: account-service
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: accounts
prop:
  value: this is prop))

