spring:
  data:
    mongodb:
      #uri: mongodb://root:root@localhost:27017/admin
       host: 10.98.53.183
       port: 27017
       username: username
       password: password
       database: account
       authentication-database: admin
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 100
      

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    
security:
  oauth2:
    client:
      clientId: account
      clientSecret: 1234
      accessTokenUri: http://localhost:9000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    #
    resource:
      user-info-uri: http://localhost:9000/uaa/user/current
      token-info-uri: http://localhost:9000/uaa/oauth/check_token

microservice:
  client:
    url: http://localhost:8099
