server:
  port: 8081

spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo1:27017,mongo1:27017/orders?replicaSet=rs0

#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      username: root
#      password: root
#      database: accounts
#       uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/orders?replicaSet=rs0

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://${DOCKER_IP}:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false

