spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/account

  zipkin:
    enabled: true
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 100


eureka:         #tells about the Eureka server details and its refresh time
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

microservice:
  client:
    url: http://localhost:8099
---

spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/account?replicaSet=rs0


  zipkin:
    enabled: true
    baseUrl: http://tracing:9411
  sleuth:
    sampler:
      probability: 100


eureka:         #tells about the Eureka server details and its refresh time
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

microservice:
  client:
    url: http://feign:8099

