server:
  port: 8087

spring:
  application:
    name: account-service
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: accounts

prop:
  value: this is prop))

