spring:
  data:
    mongodb:
      uri: mongodb://localhost:27020/admin

  zipkin:
    enabled: true
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

microservice:
  client:
    url: http://localhost:8099

