spring:
  data:
    mongodb:
      #uri: mongodb://root:root@localhost:27017/admin
       host: 10.102.26.199
       port: 27017
       username: username
       password: password
       database: account
       authentication-database: admin
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 100
      
security.oauth2.client.clientId: account
security.oauth2.client.clientSecret: '123'
security.oauth2.client.accessTokenUri: http://auth.default.svc.cluster.local:8084/uaa/oauth/token
security.oauth2.client.grant-type: client_credentials
security.oauth2.client.scope: server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

microservice:
  client:
    url: http://localhost:8099
