server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/orders?replicaSet=rs0

eureka:
   client:
     serviceUrl:
       defaultZone: ${EUREKA_SERVER:http://discovery_service:8761/eureka}
   healthcheck:
      enabled: true
   lease:
      duration: 5
     register-with-eureka: true
     fetch-registry: true

management:
  security:
    enabled: false

