spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: accounts
server:
  servlet:
    context-path: /accounts
  port: 8081
info:
  data: test