spring:
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/account?replicaSet=rs0
  zipkin:
        enabled: true
        baseUrl: http://tracing:9411
  sleuth:
    sampler:
      probability: 100

security:
  oauth2:
    client:
      clientId: account
      clientSecret: 1234
      accessTokenUri: http://auth:8084/uaa/oauth/token
      grant-type: client_credentials
      scope: server

    resource:
      user-info-uri: http://auth:8084/uaa/user/current
      token-info-uri: http://auth:8084/uaa/oauth/check_token

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

microservice:
  client:
    url: http://localhost:8099