server.port: 9998
spring.application.name: analytics
#spring.kafka.properties.schema.registry.url: http://schema-registry:8081
spring:
  cloud:
    stream:
      function.definition: process
      bindings:
        process-in-0:
          destination: quote
        process-out-0:
          destination: quote-aggregation
          producer:
            use-native-encoding: true
          
   
      kafka:
        bindings:
          process-out-0:
            producer:
              configuration:
                schema.registry.url: http://schema-registry:8081
                key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                value.serializer: org.apache.kafka.common.serialization.IntegerSerializer
          process-in-0:
            consumer:
              configuration:
                schema.registry.url: http://schema-registry:8081
                key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        streams:
          binder:
            configuration:
              schema.registry.url: http://localhost:8081
              specific.avro.reader: true



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false
