server.port: 9998
spring.application.name: analytics
spring.kafka:
  bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
  properties.allow.auto.create.topics: true
spring:
  cloud:
    stream:
      function.definition: process
      bindings:
        publish-out-0:
          destination: quote
          producer:
            use-native-encoding: true
        process-in-0:
          destination: quote
        process-out-0:
          destination: quote-aggregation
          producer:
            use-native-encoding: true
          
   
      kafka:
        binder:
          replicationFactor: 1
          #minPartitionCount: 3
          #defaultBrokerPort: kafka-1:19092,kafka-2:29092,kafka-3:39092
        bindings:
          publish-out-0:
            producer:
              configuration:
                schema.registry.url: http://localhost:8081
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: com.investment.serde.QuoteAvroSerializer
          process-in-0:
            consumer:
              configuration:
                schema.registry.url: http://localhost:8081
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: com.investment.serde.QuoteAvroSerializer
          process-out-0:
            producer:
              configuration:
                schema.registry.url: http://localhost:8081
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.apache.kafka.common.serialization.IntegerSerializer
                # com.investment.serde.QuoteAvroSerializer
  
        streams:
          binder:
            configuration:
              schema.registry.url: http://localhost:8081
              specific.avro.reader: true
          bindings:
            publish-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.investment.serde.QuoteSerde
                
            process-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
            process-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.investment.serde.QuoteSerde



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false
