server:
  port: 8083

spring:
  application:
    name: analytics-service
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: analytics
analytics:
  check:  check_servcies_changed
