server.port: 9998
spring.application.name: analytics
#spring.kafka:
#  bootstrap-servers: kafka-1:19092;kafka-2:29092;kafka-3:39092
  allow.auto.create.topics: true
spring:
  cloud:
    stream:
      function.definition: process
      bindings:
        process-in-0:
          destination: quote
        process-out-0:
          destination: quote-aggregation
          producer:
            use-native-encoding: true
          
   
      kafka:
        binder:
          #replication-factor: 1
          brokers: kafka-1;kafka-2;kafka-3
        bindings:
          process-out-0:
            producer:
              configuration:
                schema.registry.url: http://schema-registry:8081
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: com.investment.serde.QuoteAvroSerializer
          process-in-0:
            consumer:
              configuration:
                schema.registry.url: http://schema-registry:8081
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: com.investment.serde.QuoteAvroSerializer
        streams:
          binder:
            configuration:
              schema.registry.url: http://localhost:8081
              specific.avro.reader: true
          bindings:
            process-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
            process-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.investment.serde.QuoteSerde



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false
