server.port: 9998
spring.application.name: analytics
spring.zipkin.enabled: true
spring.zipkin.baseUrl: http://tracing.default.svc.cluster.local:9411
spring.cloud.stream.bindings.output:
  destination: quote-aggregation
spring.cloud.stream.bindings.input:
  destination: quote
  consumer:
    useNativeDecoding: true
spring.cloud.stream.kafka.streams.binder:
  brokers: kafka-broker.default.svc.cluster.local
  configuration:
    schema.registry.url: http://schema-registry.default.svc.cluster.local:8081
    commit.interval.ms: 1000
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
spring.cloud.stream.kafka.streams.bindings.input:
  consumer:
    keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
spring.cloud.stream.kafka.binder:
  autoAddPartitions: true
  minPartitionsCount: 2
  brokers: kafka-broker.default.svc.cluster.local
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://discovery.default.svc.cluster.local:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false
