server:
  port: 8083

spring:

  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: analytics
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://dicovery_service:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false