server:
  port: 8081
spring:
  application:
    name: analytics-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: analytics