server.port: 9998
spring.application.name: analytics
spring.kafka:
  properties:
    bootstrap-servers: pkc-4ygn6.europe-west3.gcp.confluent.cloud:9092
    properties.allow.auto.create.topics: true
    sasl.mechanism: PLAIN
    sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='IHA6RC3BC3XCYJUO' password='RBtSbbYMrHe3K6VS3LuswJDDoQ/OwnMd3AtyAqhnEN4SAvX8SIvC6T2GmW/0OEpu';
    security.protocol=: SASL_SSL
    
    basic.auth.credentials.source: USER_INFO
    basic.auth.user.info: 4JYXYBS7AXSTQRFG:Sw4ib3vEDg4lmHFcB7p7EMsMHUiaqQkQFJHC7J5fmPXDkB3TfHPiXVWMoHyfg/qc
    schema.registry.url: https://psrc-2312y.europe-west3.gcp.confluent.cloud
spring:
  cloud:
    stream:
      function.definition: process
      bindings:
        publish-out-0:
          destination: quote
          producer:
            use-native-encoding: true
        process-in-0:
          destination: quote
        process-out-0:
          destination: quote-aggregation
          producer:
            use-native-encoding: true
          
   
      kafka:
        binder:
          replicationFactor: 1
          #minPartitionCount: 3
          #defaultBrokerPort: kafka-1:19092,kafka-2:29092,kafka-3:39092
        bindings:
          publish-out-0:
            producer:
              configuration:
                schema.registry.url: http://localhost:8081
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: com.investment.serde.QuoteAvroSerializer
          process-in-0:
            consumer:
              configuration:
                schema.registry.url: http://localhost:8081
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: com.investment.serde.QuoteAvroSerializer
          process-out-0:
            producer:
              configuration:
                schema.registry.url: http://localhost:8081
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.apache.kafka.common.serialization.IntegerSerializer
                # com.investment.serde.QuoteAvroSerializer
  
        streams:
          binder:
            configuration:
              schema.registry.url: http://localhost:8081
              specific.avro.reader: true
          bindings:                
            process-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
            process-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.investment.serde.QuoteSerde



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false
