sleuth:
  sampler:
    probability: 100

eureka:
  client:
    service-url:
      defaultZone: http://discovery.default.svc.cluster.local:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

microservice:
  client:
    url: http://feign.default.svc.cluster.local:8099

security:
  oauth2:
    resource:
      user-info-uri: http://auth.default.svc.cluster.local:8084/uaa/user/current
      token-info-uri: http://auth.default.svc.cluster.local:8084/uaa/oauth/check_token
