kc:
  base-url: http://localhost:8080
  realm: My-Realm
  realm-url: ${kc.base-url}/auth/realms/${kc.realm}

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: spring-gateway-client
            client-secret: 3RhEF8pqKTANrQ6BhfxaYVmcjTXsDK0u
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          my-keycloak-provider:
            issuer-uri: ${kc.realm-url}
            jwk-set-uri: ${kc.realm-url}/protocol/openid-connect/certs
            authorization-uri: http://localhost:8080/auth/realms/My-Realm/protocol/openid-connect/auth
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/My-Realm
          jwk-set-uri: http://localhost:8080/auth/realms/My-Realm/protocol/openid-connect/certs

#management:
#  health:
#    probes.enabled: true
#    livenessState:
#      enabled: true
#    readinessState:
#      enabled: true
#  server.port: 9235
#  security:
#    enabled: false
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    refresh:
#      enabled: true
