sleuth:
  sampler:
    probability: 100

eureka:
  client:
    service-url:
      defaultZone: http://monitoring-service:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

microservice:
  client:
    url: http://feign-service:8099

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:8084/uaa/user/current
      token-info-uri: http://auth-service:8084/uaa/oauth/check_token