spring:
  data:
    mongodb:
       host: 10.102.26.199
       port: 27017
       username: username
       password: password
       database: auth
       authentication-database: admin
server:
  servlet:
    context-path: /uaa
