spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018,localhost:27019,localhost:27020/auth
      #uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/auth?replicaSet=rs0

server:
  servlet:
    context-path: /uaa

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
