spring:
  data:
    mongodb:
      uri: mongodb://root:root@mongo1:27018,mongo2:27019,mongo3:27020/auth
#      host: localhost
#      port: 27019
#      username: root
#      password: root
#      database: auth

server:
  servlet:
    context-path: /uaa