spring:
  data:
    mongodb:
       host: 10.98.53.183
       port: 27017
       username: username
       password: password
       database: auth
       authentication-database: admin
server:
  servlet:
    context-path: /uaa
security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme
    clientId: clientId
    secret: secret
    grant_type: password
    auth_host: /uaa/oauth/token
    logging.level.org.springframework.web: DEBUG
    
security.oauth2:
    client:
      clientId: feign
      clientSecret: 1234
      accessTokenUri: http://localhost:9000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    #
    resource:
      user-info-uri: http://localhost:9000/uaa/user/current
      token-info-uri: http://localhost:9000/uaa/oauth/check_token
spring.main.allow-bean-definition-overriding: true
