spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: auth


#spring:
#  data:
#    mongodb:
#      uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/auth?replicaSet=rs0
#server:
#  servlet:
#    context-path: /uaa