spring:
  data:
    mongodb:
     uri: mongodb://root:root@mongo1:27018,mongo2:27019,mongo3:27020/auth?replicaSet=rs0
      #host: localhost
      #port: 27017
      #username: root
      #password: root
      #database: admin

server:
  servlet:
    context-path: /uaa
