spring:
  data:
    mongodb:
     uri: mongodb://root:root@financial-stock-brocker_mongo3_1,financial-stock-brocker_mongo2_1,financial-stock-brocker_mongo1_1/auth
      #host: localhost
      #port: 27017
      #username: root
      #password: root
      #database: admin

server:
  servlet:
    context-path: /uaa
