spring:
  data:
    mongodb:
      uri: mongodb://user:user@localhost:27018,localhost:27019,localhost:27020/auth?replicaSet=rs0
#      host: localhost
#      port: 27019
#      username: root
#      password: root
#      database: auth

server:
  servlet:
    context-path: /uaa