spring:
  data:
    mongodb:
     uri: mongodb://mongo2:27019/auth?replicaSet=rs0
      #host: localhost
      #port: 27017
      #username: root
      #password: root
      #database: admin

server:
  servlet:
    context-path: /uaa
