spring:
  data:
    mongodb:
     uri: mongodb://user:user@mongo1,mongo2,mongo3/auth
      #host: localhost
      #port: 27017
      #username: root
      #password: root
      #database: admin

server:
  servlet:
    context-path: /uaa
