spring:
  data:
    mongodb:
     uri: mongodb://root:root@localhost:27018,localhost:27019,localhost:27020/auth
      #host: localhost
      #port: 27017
      #username: root
      #password: root
      #database: admin

server:
  servlet:
    context-path: /uaa
