spring:
  data:
    mongodb:
      #uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/feign?replicaSet=rs0
       host: localhost
       port: 27017
       username: root
       password: rootpassword
       database: feign
feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      clientId: feign
      clientSecret: 1234
      accessTokenUri: http://localhost:8084/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    #
    resource:
      user-info-uri: http://localhost:8084/uaa/user/current
      token-info-uri: http://localhost:8084/uaa/oauth/check_token
