spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - TokenRelay=
        - SaveSession
        - StripPrefix=1
      routes:
        - id: account-service
          uri: http://localhost:8093
          predicates:
           - Path=/account-service/**

        - id: order-service
          uri: http://localhost:8092
          predicates:
           - Path=/order-service/**

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  endpoints:
    web:
      exposure:
        include: routes

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 15000

  eureka:
    enabled: true
security.basic.enabled: false

server.port: 8100
