spring:
  application:
    name: gateway-service

server:
  port: 5555

zuul:
  ignoredServices:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: auth-service
      stripPrefix: false
      sensitiveHeaders:

    account-service:
      path: /accounts/**
      serviceId: account-service
      stripPrefix: false
      sensitiveHeaders:

    analytics-service:
       path: /analytics/**
       serviceId: analytics-service
       stripPrefix: false
       sensitiveHeaders:

    order-service:
       path: /order/**
       serviceId: order-service
       stripPrefix: false
       sensitiveHeaders:

    quotes-provider-service:
       path: /quotes/**
       serviceId: quotes-provider-service
       stripPrefix: false
       sensitiveHeaders:

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      eureka:
      instance:

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000



