spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: account-service
          uri: http://localhost:8093
          predicates:
           - Path=/account/**
          filters:
           - RemoveRequestHeader=Cookie
        - id: order-service
          uri: http://localhost:8092
          predicates:
           - Path=/order/**
          filters:
           - RemoveRequestHeader=Cookie


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  endpoints:
    web:
      exposure:
        include: routes

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 15000

  eureka:
    enabled: true
security.basic.enabled: false
