spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
        - StripPrefix=1
      routes:
        - id: account
          uri: http://localhost:8093
          predicates:
           - Path=/account-service/**
          filters:
           - RemoveRequestHeader=Cookie
        - id: order
          uri: http://localhost:8092
          predicates:
           - Path=/order-service/**
          filters:
           - RemoveRequestHeader=Cookie


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  endpoints:
    web:
      exposure:
        include: routes

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 15000

  eureka:
    enabled: true
