spring:
  data:
    mongodb:
#      uri: mongodb://root:root@mongo1:27018,mongo2:27019,mongo3:27020/order?replicaSet=rs0
      host: localhost
      port: 27017
      username: root
      password: root
      database: order
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

microservice:
  client:
    url: http://localhost:8099