server:
  port: 8083
spring:
  data:
    mongodb:
#      host: localhost
#        port: 27017
#        username: root
#        password: root
#        database: orders

      uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/orders?replicaSet=rs0
  profiles: default


eureka:         #tells about the Eureka server details and its refresh time
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery_service:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
