spring:
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/order?replicaSet=rs0

spring.cloud.stream.bindings.output0:
    destination: order-request
    producer:
        useNativeEncoding: true
spring.cloud.stream.bindings.output1:
    destination: order
    producer:
      useNativeEncoding: true
spring.cloud.stream.bindings.input0:
    destination: order-response
    consumer:
      useNativeDecoding: true
spring.cloud.stream.kafka.binder.brokers: broker
spring.cloud.stream.kafka.streams.binder:
    brokers: broker
    configuration:
      schema.registry.url: http://schema-registry:8081
      commit.interval.ms: 1000
      default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default.value.serde: org.springframework.kafka.support.serializer.JsonSerializer


#      com.investment.trading.kafka.serde.OrderRequestSerde
#      io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#      com.investment.trading.kafka.serde.OrderRequestSerde
#      io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

spring.cloud.stream.kafka.streams.bindings.input0:
  consumer:
    keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#    com.investment.trading.kafka.serde.OrderResponseSerde
spring.cloud.stream.kafka.streams.bindings.output0:
  producer:
    keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#    com.investment.trading.kafka.serde.OrderRequestSerde
spring.cloud.stream.kafka.streams.bindings.output1:
  producer:
    keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#    io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#    com.investment.trading.kafka.serde.OrderRequestSerde


spring.cloud.stream.kafka.binder.configuration:
    schema.registry.url: http://schema-registry:8081
    key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
#     com.investment.trading.kafka.serde.OrderRequestSerde
#    io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#    -- last ch


security.oauth2:
    client:
      clientId: order
      clientSecret: 1234
      accessTokenUri: http://auth:8084/uaa/oauth/token
      grant-type: client_credentials
      scope: server


    resource:
      user-info-uri: http://auth:8084/uaa/user/current
      token-info-uri: http://auth:8084/uaa/oauth/check_token