server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://192.168.99.100:27017,192.168.99.100:27017,192.168.99.100:27017/orders?replicaSet=rs0
  profiles: default


eureka:         #tells about the Eureka server details and its refresh time
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DOCKER_IP}:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
