server:
  port: 8082

spring:
  application:
    name: order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: orders
  profiles: dev
