spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/order
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411

  sleuth:
    sampler:
      probability: 100


eureka:         #tells about the Eureka server details and its refresh time
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

microservice:
  client:
    url: http://localhost:8099