spring:
  cloud:
    stream:
      bindings:
        output:
          producer:
            useNativeEncoding: true
          destination: quote
      kafka:
        binder:
          brokers: localhost
server.port: 9010

spring.application.name: quotes-provider-service
spring.cloud.stream.kafka.binder.configuration:
  schema.registry.url: http://localhost:8081
  key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  value.serializer: org.apache.kafka.common.serialization.Serdes$StringSerde
  #com.investment.quotesproviderservice.serdes.QuoteSerde


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false


