spring:
  application:
    name: quotes-provider-service
  cloud:
    stream:
      bindings:
        output:
          producer:
            useNativeEncoding: true
          destination: quote
      kafka:
        binder:
          brokers: broker
          configuration:
            schema.registry.url: http://schema-registry.default.svc.cluster.local:8081
            key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
            value.serializer: com.investment.quotesproviderservice.serdes.QuoteSerde

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://discovery.default.svc.cluster.local:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false

server:
  port: 9010


