apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: client
      protocol: TCP
    - port: 2888
      name: follower
      protocol: TCP
    - port: 3888
      name: leader
      protocol: TCP
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    name: kafka-broker
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: broker
    id: "0"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zookeeper
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker
spec:
  selector:
    matchLabels:
      app: kafka-broker
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-broker
        id: "0"
    spec:
      containers:
        - name: kafka-broker
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-broker.default.svc.cluster.local
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_BROKER_ID
              value: "0"
