#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: kafka-deployment
#  labels:
#    app: kafka
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: kafka
#  template:
#    metadata:
#      labels:
#        app: kafka
#    spec:
#      containers:
#        - name: kafka
#          image: confluentinc/cp-enterprise-kafka:latest
#          ports:
#            - containerPort: 9092
#          env:
#            - name: KAFKA_BROKER_ID
#              value: '1'
#            - name: KAFKA_ZOOKEEPER_CONNECT
#              value: zookeeper-service.default.svc.cluster.local:2181
#            - name: KAFKA_INTER_BROKER_LISTENER_NAME
#              value: PLAINTEXT
#            - name: KAFKA_ADVERTISED_LISTENERS
#              value: 'PLAINTEXT://kafka-service.default.svc.cluster.local:9092, SSL://kafka-service.default.svc.cluster.local:9092, PLAINTEXT_HOST://kafka-service.default.svc.cluster.local:29092'
#            - name: KAFKA_METRIC_REPORTERS
#              value: io.confluent.metrics.reporter.ConfluentMetricsReporter
#            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#              value: '1'
#            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
#              value: '0'
#            - name: CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS
#              value: kafka-service.default.svc.cluster.local:9092
#            - name: CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT
#              value: zookeeper-service.default.svc.cluster.local:2181
#            - name: CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS
#              value: '1'
#            - name: CONFLUENT_METRICS_ENABLE
#              value: 'true'
#            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#              value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
##            - name: OPENIDM_OPTS
##              value: -Djdk.tls.rejectClientInitiatedRenegotiation=true
#            - name: KAFKA_LOG4J_LOGGERS
#              value: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kafka-service
#spec:
#  selector:
#    app: kafka
#  ports:
#    - protocol: TCP
#      port: 9092
#      targetPort: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka-broker
  replicas: 1
  selector:
    matchLabels:
      kafka: kafka
  template:
    metadata:
      labels:
        kafka: kafka
    spec:
      containers:
        - image: confluentinc/cp-enterprise-kafka:5.3.0
          name: kafka
          env:
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-0.zookeeper.default.svc.cluster.local:2181
#            - name: KAFKA_LISTENERS
#              value: INTERNAL://kafka-broker.default.svc.cluster.local:29092,EXTERNAL://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://kafka-broker.default.svc.cluster.local:29092,EXTERNAL://localhost:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: '1'


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      kafka: zookeeper
  template:
    metadata:
      labels:
        kafka: zookeeper
    spec:
      containers:
        - image: confluentinc/cp-zookeeper:5.3.0
          name: kafka
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: '2181'
            - name: ZOOKEEPER_TICK_TIME
              value: '2000'

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    kafka: kafka
spec:
  ports:
    - port: 9092
      name: internal
    - port: 29092
      name: external
  selector:
    kafka: kafka

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    kafka: zookeeper
spec:
  ports:
    - port: 2181
  selector:
    kafka: zookeeper