apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-deployment
  labels:
    app: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:latest
          ports:
            - containerPort: 2181
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka-broker.default.svc.cluster.local:9092
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry.default.svc.cluster.local
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
#            - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
#              value: 'zookeeper.default.svc.cluster.local:2181'
            - name: SCHEMA_REGISTRY_DEBUG
              value: 'true'

---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081