apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing
spec:
  selector:
    matchLabels:
      app: tracing
  replicas: 1
  template:
    metadata:
      labels:
        app: tracing
    spec:
      containers:
        - name: tracing
          image: vitalii1992/tracing-service:latest #vitalii1992/tracing-service:latest #${REPOSITORY_TAG}
          ports:
            - containerPort: 9411
          imagePullPolicy: Always
          env:
            - name: TRACING_SERVICE_IMAGE
              value: "vitalii1992/tracing-service:latest"
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: '9411'

#          readinessProbe:
#            httpGet:
#              path: /eureka
#              port: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: tracing

spec:
  selector:
    app: tracing
  ports:
    - port: 9411
      protocol: TCP
  type: NodePort