apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing
spec:
  selector:
    matchLabels:
      app: tracing
  replicas: 1
  template:
    metadata:
      labels:
        app: tracing
    spec:
      containers:
        - name: tracing
          image: ${TRACING_SERVICE_IMAGE} #vitalii1992/tracing-service:latest #${REPOSITORY_TAG}
          ports:
            - containerPort: 9411
          imagePullPolicy: Always

#          readinessProbe:
#            httpGet:
#              path: /eureka
#              port: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: tracing

spec:
  selector:
    app: tracing
  ports:
    - port: 9411
      protocol: TCP
  type: NodePort