apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: kafka
  labels:
    app: postgres
data:
  POSTGRES_DB: "quotes_provider"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"