apiVersion: apps/v1
kind: Deployment
metadata:
  name: finprovider
spec:
  selector:
    matchLabels:
      app: finprovider
  replicas: 1
  template:
    metadata:
      labels:
        app: finprovider
    spec:
      containers:
        - name: finprovider
          image: vitalii1992/quotes-provider-service:latest #${REPOSITORY_TAG}
          ports:
            - containerPort: 8094
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: '8094'
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: finprovider

spec:
  ports:
    - port: 8094
      protocol: TCP
  selector:
    app: finprovider
  type: NodePort