apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth #${REPOSITORY_TAG}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: '8084'
            - name: CONFIGSERVER_URI
              value: http://configserver-service:8888
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: auth

  ports:
    - name: http
      port: 8084

  type: ClusterIP

