apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: vitalii1992/auth-service:latest #auth #${REPOSITORY_TAG}
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: PORT
              value: '8084'
            - name: AUTH_SERVICE_IMAGE
              value: "vitalii1992/auth-service:latest"
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: auth

spec:
  ports:
    - port: 8084
      protocol: TCP
  selector:
    app: auth
  type: NodePort

